# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plinterview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
