# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinterview', '0004_auto_20160423_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
